Add the ability to set stop_loss OTO orders.
d-e-s-o/apcacli pull request #2
Opened 2022-04-26 15:22 UTC by husafan

Also support bracket orders when stop_loss and take_profit are set.

2022-04-28 01:17 UTC, d-e-s-o requested changes
Thanks for the pull request! Looks mostly good, I just have a few comments.

2022-04-28 01:17 UTC, d-e-s-o commented on src/args.rs
> -
Can you please remove any spurious changes from the pull request? Thanks.

2022-04-28 01:17 UTC, d-e-s-o commented on src/args.rs
> +  /// Create a one-triggers-other order with the given stop_price under the
This documentation seems to need adjustment, now that bracket orders are supported. Same comment to the argument above and below.

2022-04-28 01:17 UTC, d-e-s-o commented on src/args.rs
> +  /// stop_loss dvanced order leg. Note that this option can only be used in
What is `dvanced`?

2022-04-28 01:17 UTC, d-e-s-o commented on src/main.rs
> +      stop_loss_limit_price.unwrap(),
Would you mind rewriting the code so that we do not require `unwrap`s? E.g., using a `match` expression,

2022-04-28 02:47 UTC, husafan commented on src/args.rs
> -
Done.

2022-04-28 03:15 UTC, husafan commented
Thank you for the quick response. Let me know if there are any other changes you'd like to see.

2022-04-29 16:30 UTC, d-e-s-o commented
Looks great now. I've merged the change with some minor modifications. Thanks for your contribution!

2022-04-29 16:30 UTC, closed without merging